Repository Pfotenclub/fabaxi, pull requests merged in 2025-03, with the labels that each got.

#101 dev_database
  app/commands/stuff.py
  app/database/mainDatabase_db.py
  app/events/karma.py
  db/__init__.py
  db/tables.py
  db/user_karma.py
  db/user_records.py
Labels: enhancement

#126 Fixed reaction karma
  app/events/karma.py
  db/user_karma.py
Labels: bug fixing

#127 added descrption to bday set command to only allow numeric values
  app/commands/stuff.py
Labels: documentation

#129 fixed another bug in karma
  app/events/karma.py
Labels: bug fixing
